config/routes.rb
Rails.application.routes.draw do
  resources :rankings do
    collection { post :import }
  end
  root 'rankings#index'
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  require 'roo'

  COLUMNS_TO_STRING = ["search_date", "search_site", "search_keyword", "search_market", "search_location",  "search_device", "google", "google_base_rank", "yahoo", "bing", "google_url", "yahoo_url", "bing_url", "advertiser_competition", "global_monthly_searches", "regional_monthly_searches", "cdc", "tags"]

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << COLUMNS_TO_STRING
      all.each do |ranking|
        csv << ranking.attributes.values_at(*COLUMNS_TO_STRING)
      end
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      row = clean_for row, COLUMNS_TO_STRING
      ranking = Ranking.find_by(:search_date => row["search_date"], :search_site => row["search_site"], :search_keyword => row["search_keyword"], :search_market => row["search_market"], :search_device => row["search_device"]) || new
      ranking.attributes = row.to_hash.slice(*row.to_hash.keys)
      ranking.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, csv_options: {col_sep: "\t"})
    when ".xls" then Roo::Excel.new(file.path)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.clean_for row_as_hash, string_columns_array
    row_as_hash.each do |key, value|
      if string_columns_array.include?key
        #row_as_hash[key] = value.to_i.to_s
        row_as_hash[key] = value.to_s
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController 
    def index
        if (params[:sdate].blank?) then params[:sdate] = "2016-02-01" end
        if (params[:edate].blank?) then params[:edate] = "2016-02-01" end
        if (params[:ranking_type].blank?) then params[:ranking_type] = "raw" end

        if params[:ranking_type].to_s == "average"
        ranking = Ranking.select("search_date, avg(google) as google, avg(yahoo) as yahoo, avg(bing) as bing").where("search_date >= ? AND search_date <= ?", params[:sdate], params[:edate]).group("search_date");
        @rankings = ranking.paginate(:page => params[:page], :per_page => 30)
        elsif params[:ranking_type].to_s == "weighted"
        ranking = Ranking.select("search_date, avg(global_monthly_searches) avg_global, max(global_monthly_searches) as max_global, avg(google) as google, avg(yahoo) as yahoo, avg(bing) as bing").where("search_date >= ? AND search_date <= ?", params[:sdate], params[:edate]).group("search_date");
        @rankings = ranking.paginate(:page => params[:page], :per_page => 30)
        else
        ranking = Ranking.where("search_date >= ? AND search_date <= ?", params[:sdate], params[:sdate])
        @rankings = ranking.paginate(:page => params[:page], :per_page => 30)
        end
        response do |format|
           format.html
           format.csv { send_data @rankings.to_csv }
           format.xls # { send_data @rankings.to_csv(col_sep: "\t") }
        end
    end

    def import
        Ranking.import(params[:file])
        redirect_to root_url, notice: "Rankings imported."
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeoStat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rankings/_search_average.html.erb
<table id="rankings">
    <tr>
        <td>Date</td>
        <td>Google</td>
        <td>Yahoo</td>
        <td>Bing</td>
    </tr>
    <% @rankings.each do |ranking| %>
    <tr>
        <td><%= ranking.search_date %></td>
        <td><%= ranking.google %></td>
        <td><%= ranking.yahoo %></td>
        <td><%= ranking.bing %></td>
    </tr>
    <% end %>
</table>

app/views/rankings/_search_raw.html.erb
<table id="rankings">
    <tr>
        <td>Date</td>
        <td>Site</td>
        <td>Keyword</td>
        <td>Market</td>
        <td>Location</td>
        <td>Device</td>
        <td>Google</td>
        <td>Google Bank Rank</td>
        <td>Yahoo</td>
        <td>Bing</td>
        <td>Google Url</td>
        <td>Yahoo Url</td>
        <td>Bing Url</td>
        <td>Advertiser Competition</td>
        <td>Global Monthly Searches</td>
        <td>Regional Monthly Searches</td>
        <td>CDC</td>
        <td>Tags</td>
    </tr>
    <% @rankings.each do |ranking| %>
    <tr>
        <td><%= ranking.search_date %></td>
        <td><%= ranking.search_site %></td>
        <td><%= ranking.search_keyword %></td>
        <td><%= ranking.search_market %></td>
        <td><%= ranking.search_location %></td>
        <td><%= ranking.search_device %></td>
        <td><%= ranking.google %></td>
        <td><%= ranking.google_base_rank %></td>
        <td><%= ranking.yahoo %></td>
        <td><%= ranking.bing %></td>
        <td><%= ranking.google_url %></td>
        <td><%= ranking.yahoo_url %></td>
        <td><%= ranking.bing_url %></td>
        <td><%= ranking.advertiser_competition %></td>
        <td><%= ranking.global_monthly_searches %></td>
        <td><%= ranking.regional_monthly_searches %></td>
        <td><%= ranking.cdc %></td>
        <td><%= ranking.tags %></td>
    </tr>
    <% end %>
</table>

app/views/rankings/_search_weighted.html.erb
<table id="rankings">
    <tr>
        <td>Date</td>
        <td>Google</td>
        <td>Yahoo</td>
        <td>Bing</td>
    </tr>
    <% @rankings.each do |ranking| %>
    <tr>
        <td><%= ranking.search_date %></td>
        <td><%= (ranking.google * ranking.avg_global / ranking.max_global).round(4) %></td>
        <td><%= (ranking.yahoo * ranking.avg_global / ranking.max_global).round(4) %></td>
        <td><%= (ranking.bing * ranking.avg_global / ranking.max_global).round(4) %></td>
    </tr>
    <% end %>
</table>

app/views/rankings/index.csv.erb
Date,Site,Keyword,Market,Location,Device,Google,Google Bank Rank,Yahoo,Bing,Google Url,Yahoo Url,Bing Url,Advertiser Competition,Global Monthly Searches,Regional Monthly Searches,CDC,Tags
<% @rankings.each do |ranking| %>
<%= ranking.search_date %>,<%= ranking.search_site %>,<%= ranking.search_keyword %>,<%= ranking.search_market %>,<%= ranking.search_location %>,<%= ranking.search_device %>,<%= ranking.google %>,<%= ranking.google_base_rank %>,<%= ranking.yahoo %>,<%= ranking.bing %>,<%= ranking.google_url %>,<%= ranking.yahoo_url %>,<%= ranking.bing_url %>,<%= ranking.advertiser_competition %>,<%= ranking.global_monthly_searches %>,<%= ranking.regional_monthly_searches %>,<%= ranking.cdc %>,<%= ranking.tags %>
<% end %>

app/views/rankings/index.html.erb
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <div id="brand" class="brand">Search Ranking</div>
                    </div>
                </div>
            </div>
        </div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="well">
        <table border="0" width="100%">
          <tr>
            <td width="200"><div class="control-group"><label class="control-label"><b>Import Ranking CSV File</b></lable></div></td>
            </td>
            <td><div id="txt" class="control-group">
<%= form_tag import_rankings_path, multipart:true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>
            </td>
          <tr>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="well">
        <table border="0" width="100%">
          <tr>
            <td width="200"><div class="control-group"><label class="control-label"><b>Search Date</b></lable></div></td>
            <td><div id="txt" class="control-group">
<%= text_field "ranking", "sdate", "size" => 10, "value" => params[:sdate].to_s %> ~
<%= text_field "ranking", "edate", "size" => 10, "value" => params[:edate].to_s %>
            </td>
          <tr>
          <tr>
            <td width="200"><div class="control-group"><label class="control-label"><b>Search Type</b></lable></div></td>
            <td><div id="txt" class="control-group">
<%= radio_button_tag 'ranking_type', 'raw', !!(params[:ranking_type].to_s == "raw") %> Raw
<%= radio_button_tag 'ranking_type', 'average', !!(params[:ranking_type].to_s == "average") %> Average
<%= radio_button_tag 'ranking_type', 'weighted', !!(params[:ranking_type].to_s == "weighted") %> Weighted
            </td>
          <tr>
        </table>
<script >
    $(function(){
        function getUrl() {
            var sdate = document.getElementById("ranking_sdate").value;
            var edate = document.getElementById("ranking_edate").value;
            var search_type = $("input[name=ranking_type]:checked").val();
            var root_path = "<%= root_path %>"
            var url = root_path + "?ranking_type=" + search_type + "&sdate=" + sdate + "&edate=" + edate;
            return url;
        }

        $("input[id=ranking_sdate]").change(function(){
            var url = getUrl();
            window.location.replace(url);
        });
        $("input[id=ranking_edate]").change(function(){
            var url = getUrl();
            window.location.replace(url);
        });
        $("input[name=ranking_type]").click(function(){
            var url = getUrl();
            window.location.replace(url);
        });
    });
</script>
      </div>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="CSSTableGenerator">
    <div id="txt" class="control-group">
    Download:
    <%= link_to "CSV", rankings_path(format: "csv") %> |
    <%= link_to "Excel", rankings_path(format: "xls") %>
    </div>
    <div id="txt" class="control-group">
    <% if params[:ranking_type] == "average" %>
        <%= render "rankings/search_average" %>
    <% elsif params[:ranking_type] == "weighted" %>
        <%= render "rankings/search_weighted" %>
    <% else %>
        <%= render "rankings/search_raw" %>
    <% end %>
    </div>
    <div id="txt" class="control-group">
        <%= will_paginate @rankings %>
    </div>
  </div>
</div>

app/views/rankings/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Site</Data></Cell>
        <Cell><Data ss:Type="String">Keyword</Data></Cell>
        <Cell><Data ss:Type="String">Market</Data></Cell>
        <Cell><Data ss:Type="String">Location</Data></Cell>
        <Cell><Data ss:Type="String">Device</Data></Cell>
        <Cell><Data ss:Type="String">Google</Data></Cell>
        <Cell><Data ss:Type="String">Google Bank Rank</Data></Cell>
        <Cell><Data ss:Type="String">Yahoo</Data></Cell>
        <Cell><Data ss:Type="String">Bing</Data></Cell>
        <Cell><Data ss:Type="String">Google Url</Data></Cell>
        <Cell><Data ss:Type="String">Yahoo Url</Data></Cell>
        <Cell><Data ss:Type="String">Bing Url</Data></Cell>
        <Cell><Data ss:Type="String">Advertiser Competition</Data></Cell>
        <Cell><Data ss:Type="String">Global Monthly Searches</Data></Cell>
        <Cell><Data ss:Type="String">Regional Monthly Searches</Data></Cell>
        <Cell><Data ss:Type="String">CDC</Data></Cell>
        <Cell><Data ss:Type="String">Tags</Data></Cell>
      </Row>
    <% @rankings.each do |ranking| %>
      <Row>
        <Cell><Data ss:Type="String"><%= ranking.search_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.search_site %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.search_keyword %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.search_market %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.search_location %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.search_device %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.google %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.google_base_rank %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.yahoo %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.bing %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.google_url %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.yahoo_url %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.bing_url %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.advertiser_competition %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.global_monthly_searches %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.regional_monthly_searches %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.cdc %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ranking.tags %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>